version: '3.8'
services:
  nztz-client:
    build: .
    container_name: nezha-agent-web
    restart: always
    ports:
      - "80:80"
    environment:
      - NZ_CLIENT_SECRET=p3joFK1jc3Z31YXqMXfNPvjjxx1lQknL
