# 以后你只需要在这个文件里增加 listen 行
server {
    listen 5000;
    listen 3000;
    listen 8080;
    listen 80;

    # 以下内容不要动，确保网页正常显示
    server_name _;
    root /var/www/localhost/html;
    index index.html;
    location / {
        try_files $uri $uri/ =404;
    }
}
